uid = 1
t = 0.0

[[element]]
    name = "Planet"
    nbody = true
    config = "system/planet/planet.toml"
    rotation_period = 24.0
    rotation_at_epoch = 0.0

    [element.position]
        x = 0
        y = 0
        z = 0

    [element.velocity]
        x = 0
        y = 0
        z = 0

    [element.rotation_axis]
        x = 0
        y = 1.0
        z = 0
